-- Integracion de pagos Mercado Pago (suscripcion automatica y pago mensual manual)

create table if not exists public.payment_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  provider text not null default 'mercadopago' check (provider in ('mercadopago')),
  mode text not null check (mode in ('recurring', 'one_time')),
  plan_code text not null check (plan_code in ('monthly', 'annual', 'monthly_manual')),
  status text not null default 'pending',
  provider_preapproval_id text,
  provider_payment_id text,
  provider_plan_id text,
  external_reference text,
  payer_email text,
  amount numeric(12,2),
  currency text not null default 'ARS',
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  last_event_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create unique index if not exists idx_payment_subscriptions_provider_preapproval_id
  on public.payment_subscriptions(provider_preapproval_id)
  where provider_preapproval_id is not null;

create unique index if not exists idx_payment_subscriptions_provider_payment_id
  on public.payment_subscriptions(provider_payment_id)
  where provider_payment_id is not null;

create index if not exists idx_payment_subscriptions_user_id
  on public.payment_subscriptions(user_id);

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  event_type text,
  payload jsonb not null,
  processed boolean not null default false,
  processed_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  unique(provider, event_id)
);

create index if not exists idx_payment_webhook_events_provider_created_at
  on public.payment_webhook_events(provider, created_at desc);

alter table public.payment_subscriptions enable row level security;
alter table public.payment_webhook_events enable row level security;

drop policy if exists "Users can view own payment subscriptions" on public.payment_subscriptions;
create policy "Users can view own payment subscriptions"
  on public.payment_subscriptions
  for select
  using (auth.uid() = user_id);
